### ISSUE TITLE
Magdalena Link

### ISSUE THREAD

**Issue by arnim** [gesiscss/mh_tutorial#8]
Link to [magdalena](https://git.gesis.org/methods-hub/magdalena) in the readme is to a non public repo.

**Comment by chainsawriot** [comment]
[[^1]: Access to the code of magdalena is not public.](https://github.com/gesiscss/mh_tutorial/blob/19f72335aadf59e2fb0a9e6f60591b4882ba9556/readme.md?plain=1#L91)
